owner: JosueElara
repo: status

sites:
  - name: Elara.LI URL Shortener
    url: https://elara.li
    __dangerous__body_down: "Ray ID"
  - name: Kaia by Elara
    url: https://kaia.elara.li
    __dangerous__body_down: "Ray ID"

status-website:
  cname: status.elara.li
  name: Elara Status
  introTitle: "Status of **Elara** Services"
  introMessage: This platform actively monitors the status of Elara services.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://elara.li
    - title: GitHub
      href: https://github.com/JosueElara/status
